feat(eslint): Migration to eslint from tslint
Ryanair/linters pull request #33
Opened 2021-01-27 13:40 UTC by billorer

fix #migrate-tslint-to-eslint

2021-01-27 13:51 UTC, dudyn5ky1 requested changes

2021-01-27 13:51 UTC, dudyn5ky1 commented on packages/eslint-plugin/.eslintrc
> +      "project": "./tsconfig.eslint.json",
this file is not linted

2021-01-27 14:29 UTC, billorer commented on packages/eslint-plugin/.eslintrc
> +      "project": "./tsconfig.eslint.json",
done

2021-01-28 09:34 UTC, dudyn5ky1 approved these changes

2021-01-29 21:08 UTC, merged

2021-01-29 21:08 UTC, izifortune commented
Thanks  @billorer  thats now merged